### ISSUE TITLE
toolbar icons don't appear on IE

### ISSUE THREAD

**Issue by JonathanReeve** [clrux/a11y#3] opened 2014-10-31 20:33 UTC
The a11y toolbar icons look fine for me in Firefox and Chromium, but on IE they don't display at all--it's just an empty gray toolbar.

**Comment by clrux** [comment] 2015-04-01 01:59
@JonathanReeve Thanks for the issue submission. I've been extremely busy lately, but hope to get to this fix sometime soon. Feel free to create a PR if you're so inclined. I'd welcome the assistance!

**Comment by XhmikosR** [comment] 2015-09-28 16:39
Personally, I can't reproduce this.

**Comment by XhmikosR** [comment] 2015-09-28 17:15
I should clarify, I tested with https://github.com/joedolson/wp-accessibility/

**Comment by clrux** [comment] 2015-09-29 02:18
I'm going to close this issue as I'm currently in the process of revamping this plugin from the ground up. Once it's released, feel free to create new issues on things you may find. Thank you.

**Closed by clrux** 2015-09-29 02:18 UTC
